apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContext: arista-ceoslab-operator-test
testDirs:
- test
manifestDirs:
- config/kustomized
kindContainers:
- ghcr.io/aristanetworks/arista-ceoslab-operator:v0.2.0
- ceos:latest
- ceos-2:latest
- networkop/init-wait:latest
- networkop/init-wait-2:latest
skipDelete: true
skipClusterDelete: true
# The default timeout of 30 seconds is much to short for ceos to boot reliably
timeout: 120
